# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aki', models.CharField(default='', max_length=50)),
                ('Aks', models.CharField(default='', max_length=50)),
                ('Domain_name', models.CharField(default='', max_length=50)),
                ('server', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='service_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=255)),
                ('l2tp', models.CharField(default='', max_length=255)),
                ('ssl', models.CharField(default='', max_length=255)),
                ('re', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
