# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181016_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_info',
            name='end_time',
            field=models.DateField(),
        ),
    ]
