# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20181016_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_info',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
