# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_command_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_info',
            name='action_time',
        ),
        migrations.RemoveField(
            model_name='task_info',
            name='end_time',
        ),
    ]
