# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20181019_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_info',
            name='user',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
