# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_task_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_info',
            name='br_ip',
        ),
        migrations.AddField(
            model_name='service_info',
            name='abroad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service_info',
            name='cpuinfo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service_info',
            name='diskinfo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service_info',
            name='service_port',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='service_info',
            name='within',
            field=models.CharField(default='', max_length=255),
        ),
    ]
