# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20181024_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_info',
            name='meminfo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_info',
            name='service_port',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
