# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20181024_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='command_list',
        ),
        migrations.DeleteModel(
            name='Task_info',
        ),
    ]
