# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20181025_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('Host', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
