# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_domain_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain_info',
            old_name='type',
            new_name='Type',
        ),
    ]
