# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_blog_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_settings',
            name='content',
        ),
        migrations.AddField(
            model_name='blog_settings',
            name='Aki',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog_settings',
            name='Aks',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog_settings',
            name='Domain_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog_settings',
            name='server',
            field=models.CharField(default='', max_length=255),
        ),
    ]
