# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='\u64cd\u4f5c\u547d\u4ee4', max_length=500)),
                ('start_time', models.CharField(max_length=255)),
                ('user', models.CharField(default='user', max_length=50)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
