# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181025_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='re_cm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='remote_cmd',
            name='cmd',
        ),
    ]
